# Generated by Django 5.2.9 on 2025-12-19 11:40

import bot_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(default='uz', max_length=50)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('total_rides', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Yo'lovchi",
                'verbose_name_plural': "Yo'lovchilar",
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='PassengerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('from_location', models.JSONField(default=bot_app.models.default_location)),
                ('to_location', models.JSONField(default=bot_app.models.default_location)),
                ('price', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('destination', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pochta',
                'verbose_name_plural': 'Pochtalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('from_location', models.JSONField(default=bot_app.models.default_location)),
                ('to_location', models.JSONField(default=bot_app.models.default_location)),
                ('price', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('destination', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='standard', max_length=200)),
                ('passenger', models.IntegerField(default=1)),
                ('has_woman', models.BooleanField(default=False)),
                ('rate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sayohat',
                'verbose_name_plural': 'Sayohatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('translate', models.JSONField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.city')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comfort', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_app.city')),
            ],
            options={
                'verbose_name': 'Shahar narxlari',
                'verbose_name_plural': 'Shahar narxlari',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(default='', max_length=200)),
                ('total_rides', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rating', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10)),
                ('amount', models.IntegerField(default=150000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_from', related_query_name='driver_from', to='bot_app.city')),
                ('to_location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_to', related_query_name='driver_to', to='bot_app.city')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=200, unique=True)),
                ('car_model', models.CharField(max_length=200)),
                ('car_color', models.CharField(max_length=200)),
                ('car_class', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='economy', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='bot_app.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('telegram_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.driver')),
            ],
            options={
                'verbose_name': "Haydovchi pul o'tkazmasi",
                'verbose_name_plural': "Haydovchi pul o'tkazmalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10)),
                ('order_type', models.CharField(choices=[('travel', 'Travel'), ('delivery', 'Delivery')], default='travel', max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.driver')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
